CREATE ROLE LIBRARY_ROLE;

GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE, CREATE TRIGGER TO LIBRARAY_ROLE;


CREATE PROFILE LIBRARY_PROFILE
LIMIT
FAILED_LOGIN_ATTEMPTS 3
PASSWORD_LIFE_TIME 90
SESSIONS_PER_USER 2;


CREATE USER LIBRARY_ADMIN
IDENTIFIED BY library123
DEFAULT TABLESPACE LIBRARY_TBS
TEMPORARY TABLESPACE TEMP
PROFILE LIBRARY_PROFILE
QUOTA UNLIMITED ON LIBRARY_TBS;


GRANT LIBRARY_ROLE TO LIBRARY_ADMIN;
