CREATE SEQUENCE SEQ_BOOK_ID
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE TABLE BOOKS
(
    BOOK_ID NUMBER,
    TITLE VARCHAR2(100) NOT NULL,
    AUTHOR VARCHAR2(100) NOT NULL,
    ISBN VARCHAR2(20),
    CATEGORY VARCHAR2(20),
    PUBLISHER VARCHAR2(20),
    CREATE_DATE DATE,

    CONSTRAINT PK_BOOKS
    PRIMARY KEY (BOOK_ID),

    CONSTRAINT UK_BOOK_ISBN
    UNIQUE (ISBN)
);

CREATE OR REPLACE TRIGGER TRG_BOOK_ID
BEFORE INSERT ON BOOKS
FOR EACH ROW
BEGIN
    :NEW.BOOK_ID := SEQ_BOOK_ID.NEXTVAL;
END;
/
