CREATE SEQUENCE SEQ_MEMBER_ID
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE TABLE MEMBERS
(
    MEMBER_ID NUMBER,
    MEMBER_NAME VARCHAR2(100) NOT NULL,
    PHONE VARCHAR2(15),
    JOIN_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT PK_MEMBERS
    PRIMARY KEY (MEMBER_ID),

    CONSTRAINT UK_MEMBER_PHONE
    UNIQUE (PHONE)
);

CREATE OR REPLACE TRIGGER TRG_MEMBER_ID
BEFORE INSERT ON MEMBERS
FOR EACH ROW
BEGIN
    :NEW.MEMBER_ID := SEQ_MEMBER_ID.NEXTVAL;
END;
/
