CREATE SEQUENCE SEQ_COPY_ID
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE TABLE BOOK_COPIES
(
    COPY_ID NUMBER,
    BOOK_ID NUMBER NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'AVAILABLE',

    CONSTRAINT PK_BOOK_COPIES
    PRIMARY KEY (COPY_ID),

    CONSTRAINT FK_COPY_BOOK
    FOREIGN KEY (BOOK_ID)
    REFERENCES BOOKS (BOOK_ID)
);

CREATE OR REPLACE TRIGGER TRG_COPY_ID
BEFORE INSERT ON BOOK_COPIES
FOR EACH ROW
BEGIN
    :NEW.COPY_ID := SEQ_COPY_ID.NEXTVAL;
END;
/
