CREATE SEQUENCE SEQ_ISSUE_ID
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE TABLE ISSUES
(
    ISSUE_ID NUMBER,
    COPY_ID NUMBER NOT NULL,
    MEMBER_ID NUMBER NOT NULL,
    ISSUE_DATE DATE DEFAULT SYSDATE,
    DUE_DATE DATE,

    CONSTRAINT PK_ISSUES
    PRIMARY KEY (ISSUE_ID),

    CONSTRAINT FK_ISSUES_COPY
    FOREIGN KEY (COPY_ID)
    REFERENCES BOOK_COPIES (COPY_ID),

    CONSTRAINT FK_ISSUES_MEMBER
    FOREIGN KEY (MEMBER_ID)
    REFERENCES MEMBERS (MEMBER_ID)
);

CREATE OR REPLACE TRIGGER TRG_ISSUE_ID
BEFORE INSERT ON ISSUES
FOR EACH ROW
BEGIN
    :NEW.ISSUE_ID := SEQ_ISSUE_ID.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_ISSUE_BOOK
AFTER INSERT ON ISSUES
FOR EACH ROW
BEGIN
    UPDATE BOOK_COPIES
    SET STATUS='ISSUED'
    WHERE COPY_ID=:NEW.COPY_ID;
END;
/
