CREATE SEQUENCE SEQ_RETURN_ID
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE TABLE RETURNS
(
    RETURN_ID NUMBER,
    ISSUE_ID NUMBER NOT NULL,
    RETURN_DATE DATE DEFAULT SYSDATE,
    FINE NUMBER(6,2) DEFAULT 0,

    CONSTRAINT PK_RETURNS
    PRIMARY KEY (RETURN_ID),

    CONSTRAINT FK_RETURNS_ISSUE
    FOREIGN KEY (ISSUE_ID)
    REFERENCES ISSUES (ISSUE_ID)
);

CREATE OR REPLACE TRIGGER TRG_RETURN_ID
BEFORE INSERT ON RETURNS
FOR EACH ROW
BEGIN
    :NEW.RETURN_ID := SEQ_RETURN_ID.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_RETURN_BOOK
AFTER INSERT ON RETURNS
FOR EACH ROW
BEGIN
    UPDATE BOOK_COPIES
    SET STATUS='AVAILABLE'
    WHERE COPY_ID =
    (
        SELECT COPY_ID
        FROM ISSUES
        WHERE ISSUE_ID=:NEW.ISSUE_ID
    );
END;
/
