CREATE OR REPLACE VIEW VW_AVAILABLE_BOOKS
AS
SELECT
    B.BOOK_ID,
    B.TITLE,
    BC.COPY_ID,
    BC.STATUS
FROM BOOKS B,
     BOOK_COPIES BC
WHERE B.BOOK_ID = BC.BOOK_ID
AND BC.STATUS='AVAILABLE';


CREATE OR REPLACE VIEW VW_ISSUED_BOOKS
AS
SELECT
    I.ISSUE_ID,
    M.MEMBER_NAME,
    B.TITLE,
    I.ISSUE_DATE,
    I.DUE_DATE
FROM ISSUES I,
     MEMBERS M,
     BOOK_COPIES BC,
     BOOKS B
WHERE I.MEMBER_ID=M.MEMBER_ID
AND I.COPY_ID=BC.COPY_ID
AND BC.BOOK_ID=B.BOOK_ID;


CREATE OR REPLACE VIEW VW_CURRENT_ISSUES
AS
SELECT
    I.ISSUE_ID,
    I.COPY_ID,
    I.MEMBER_ID,
    I.ISSUE_DATE,
    I.DUE_DATE
FROM ISSUES I
WHERE NOT EXISTS
(
    SELECT 1
    FROM RETURNS R
    WHERE R.ISSUE_ID=I.ISSUE_ID
);
